name: CI
on: [push, pull_request]
jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: '8.1'
            wordpress: '6.1'
            analysis: true
          - php: '8.0'
            wordpress: '5.9'
          - php: '5.6'
            wordpress: '4.7'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          coverage: xdebug
      - name: Setup DB
        run: sudo /etc/init.d/mysql start
      - name: Setup WP
        run: bash bin/install-wp-tests.sh wordpress root root localhost "${{ matrix.wordpress }}"
      - name: Install
        run: composer install --no-interaction
      - name: Test
        run: vendor/bin/phpunit --coverage-clover phpunit.coverage.xml --log-junit  phpunit.report.xml
      - name: Analyze with SonarCloud
        if: matrix.analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=stklcode-github
            -Dsonar.projectKey=stklcode:wp-liveticker
            -Dsonar.sources=includes,scripts,views,stklcode-liveticker.php
            -Dsonar.tests=tests
            -Dsonar.exclusions=scripts/*.min.js,styles/*.min.css
