name: CI
on: push
jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: '7.4'
            wordpress: '5.7'
          - php: '5.6'
            wordpress: '4.7'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
      - name: Setup DB
        run: sudo /etc/init.d/mysql start
      - name: Setup WP
        run: bash bin/install-wp-tests.sh wordpress root root localhost "${{ matrix.wordpress }}"
      - name: Install
        run: composer install
      - name: Test
        run: composer test

  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install
        run: |
          composer install --no-interaction
          npm ci
      - name: Code style checks for PHP, JS and CSS
        run: |
          composer lint-php
          composer lint-js
          composer lint-css

  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=stklcode-github
            -Dsonar.projectKey=stklcode:wp-liveticker
            -Dsonar.sources=includes,scripts,views,stklcode-liveticker.php
            -Dsonar.exclusions=scripts/*.min.js,styles/*.min.css
