name: Deploy to WordPress.org
on:
  push:
    tags:
      - "v*"
      - "!v*-*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: Clean README.md
        run: tail -n +7 README.md > README.md.tmp && mv README.md.tmp README.md
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          ASSETS_DIR: assets
          SVN_PASSWORD: ${{ secrets.WP_SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.WP_SVN_USERNAME }}
