name: Plugin asset/readme update
on:
  push:
    branches:
      - stable
jobs:
  master:
    name: Push to stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
      - name: Install
        run: composer install --no-interaction
      - name: Clean README.md
        run: tail -n +7 README.md > README.md.tmp && mv README.md.tmp README.md
      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SLUG: stklcode-liveticker
          ASSETS_DIR: assets
          README_NAME: README.md
          SVN_PASSWORD: ${{ secrets.WP_SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.WP_SVN_USERNAME }}
